spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

queue:
  engineRequestQueue: md2doc-engine-queue

transform:
  core:
    version: 5.2.5
  pandoc:
    toc:
      enabled: false
      depth: 3
    pdf:
      engine: xelatex
